// <auto-generated />
using System;
using LightYear.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LightYear.Migrations
{
    [DbContext(typeof(LightYearContext))]
    [Migration("20200226210426_Reinitialize")]
    partial class Reinitialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LightYear.Models.GameState", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("p1Damage");

                    b.Property<int>("p1Population");

                    b.Property<bool>("p1Turn");

                    b.Property<int>("p2Damage");

                    b.Property<int>("p2Population");

                    b.Property<bool>("p2Turn");

                    b.Property<int>("turnNumber");

                    b.HasKey("GameId");

                    b.ToTable("Instances");
                });

            modelBuilder.Entity("LightYear.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedAt");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name");

                    b.Property<int>("PlayerState");

                    b.Property<DateTime>("UpdatedAt");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("LightYear.Models.Ship", b =>
                {
                    b.Property<int>("ShipId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Damage");

                    b.Property<int>("GameId");

                    b.Property<int>("Health");

                    b.Property<int?>("PlayerId");

                    b.Property<int>("PlayerState");

                    b.HasKey("ShipId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Ships");
                });

            modelBuilder.Entity("LightYear.Models.Ship", b =>
                {
                    b.HasOne("LightYear.Models.Player")
                        .WithMany("Armada")
                        .HasForeignKey("PlayerId");
                });
#pragma warning restore 612, 618
        }
    }
}
